export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const ADD_BLANK_QUESTION = 'ADD_BLANK_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const RESET_PAPER = 'RESET_PAPER';
